image:
  name: hashicorp/terraform:1.1.7

stages:
  - init
  - validate
  - plan
  - apply
  - destroy

variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_STATE_NAME: ${TF_STATE_NAME:-default}

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

init:
  stage: init
  script:
    - cd ${TF_ROOT}
    - terraform init

validate:
  stage: validate
  script:
    - terraform validate
    
plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy
  script:
    - cd ${TF_ROOT}
    - terraform destroy
  resource_group: ${TF_STATE_NAME}
  when: manual
