stages:
  - init
  - validate
  - plan
  - apply
  - destroy

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}'
    - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'
    - 'AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}'

variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_STATE_NAME: ${TF_STATE_NAME:-default}

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

init:
  stage: init
  script:
    - rm -rf .terraform
    - terraform --version
    - terraform init

validate:
  stage: validate
  script:
    - terraform validate
    
plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy
  script:
    - cd ${TF_ROOT}
    - terraform destroy
  resource_group: ${TF_STATE_NAME}
  when: manual
